/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bebidas;

/**
 *
 * @author jujuf
 */
public class Bebidas extends javax.swing.JFrame {

    /**
     * Creates new form Bebidas
     */
    public Bebidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AtivarButton = new javax.swing.JButton();
        FrapuccinoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AtivarButton.setText("jButton1");
        AtivarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtivarButtonMouseClicked(evt);
            }
        });
        AtivarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtivarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AtivarButton);
        AtivarButton.setBounds(20, 200, 40, 50);

        FrapuccinoButton.setText("jButton2");
        FrapuccinoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrapuccinoButtonMouseClicked(evt);
            }
        });
        FrapuccinoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrapuccinoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FrapuccinoButton);
        FrapuccinoButton.setBounds(60, 190, 110, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bebidas.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtivarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtivarButtonActionPerformed
        BebidasAtivado batv = new BebidasAtivado();
        batv.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_AtivarButtonActionPerformed

    private void FrapuccinoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrapuccinoButtonActionPerformed
       EscolhaBebidas esc = new EscolhaBebidas();
       esc.setAlwaysOnTop (true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_FrapuccinoButtonActionPerformed

    private void AtivarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtivarButtonMouseClicked
     BebidasAtivado batv = new BebidasAtivado();
        batv.setVisible(true);
        this.dispose();
   // TODO add your handling code here:
    }//GEN-LAST:event_AtivarButtonMouseClicked

    private void FrapuccinoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrapuccinoButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FrapuccinoButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtivarButton;
    private javax.swing.JButton FrapuccinoButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
