/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bebidas;

/**
 *
 * @author jujuf
 */
public class EscolhaBebidas extends javax.swing.JFrame {
    private int num = 0;
    /**
     * Creates new form EscolhaBebidas
     */
    public EscolhaBebidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoltarAtivado = new javax.swing.JButton();
        MorangoButton = new javax.swing.JButton();
        chocolatebutton = new javax.swing.JButton();
        semcaldabutton = new javax.swing.JButton();
        aumenta = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        qnt = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        VoltarAtivado.setText("jButton1");
        VoltarAtivado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarAtivadoMouseClicked(evt);
            }
        });
        VoltarAtivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAtivadoActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarAtivado);
        VoltarAtivado.setBounds(55, 10, 40, 50);

        MorangoButton.setText("jButton1");
        MorangoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MorangoButtonMouseClicked(evt);
            }
        });
        MorangoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorangoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MorangoButton);
        MorangoButton.setBounds(665, 200, 30, 23);

        chocolatebutton.setText("jButton1");
        chocolatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(chocolatebutton);
        chocolatebutton.setBounds(665, 250, 30, 20);

        semcaldabutton.setText("jButton2");
        semcaldabutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semcaldabuttonMouseClicked(evt);
            }
        });
        getContentPane().add(semcaldabutton);
        semcaldabutton.setBounds(665, 290, 30, 23);

        aumenta.setText("jButton1");
        aumenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentaActionPerformed(evt);
            }
        });
        getContentPane().add(aumenta);
        aumenta.setBounds(625, 460, 30, 40);

        menos.setText("jButton1");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        getContentPane().add(menos);
        menos.setBounds(550, 460, 30, 40);

        qnt.setText("jLabel2");
        getContentPane().add(qnt);
        qnt.setBounds(580, 470, 37, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EscolhaBebidas.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarAtivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAtivadoActionPerformed
        Bebidas beb = new Bebidas();
        beb.setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarAtivadoActionPerformed

    private void MorangoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorangoButtonActionPerformed
        EscolhaMorango mor = new EscolhaMorango();
        mor.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_MorangoButtonActionPerformed

    private void VoltarAtivadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarAtivadoMouseClicked
       BebidasAtivado batv = new BebidasAtivado();
        batv.setVisible(true);
        batv.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarAtivadoMouseClicked

    private void MorangoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MorangoButtonMouseClicked
       EscolhaMorango mor = new EscolhaMorango();
        mor.setVisible(true);
        mor.dispose();   
// TODO add your handling code here:
    }//GEN-LAST:event_MorangoButtonMouseClicked

    private void chocolatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolatebuttonActionPerformed
       EscolhaChocolate cho = new EscolhaChocolate();
        cho.setVisible(true);
        cho.dispose();  
        // TODO add your handling code here:
    }//GEN-LAST:event_chocolatebuttonActionPerformed

    private void semcaldabuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semcaldabuttonMouseClicked
       EscolhaSemCalda sem = new EscolhaSemCalda();
        sem.setVisible(true);
        sem.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_semcaldabuttonMouseClicked

    private void aumentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentaActionPerformed
        num++;
        qnt.setText(String.valueOf(num));
        // TODO add your handling code here:
    }//GEN-LAST:event_aumentaActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
         num--;
        qnt.setText(String.valueOf(num));
// TODO add your handling code here:
    }//GEN-LAST:event_menosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaBebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MorangoButton;
    private javax.swing.JButton VoltarAtivado;
    private javax.swing.JButton aumenta;
    private javax.swing.JButton chocolatebutton;
    private javax.swing.JButton menos;
    private javax.swing.JLabel qnt;
    private javax.swing.JButton semcaldabutton;
    // End of variables declaration//GEN-END:variables
}
